services:
  balanced-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: balanced-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=balanced-db
      - DB_PORT=5432
      - DB_NAME=balanced
      - DB_USERNAME=balanced
      - DB_PASSWORD=balanced
    depends_on:
      balanced-db:
        condition: service_healthy
    networks:
      - balanced-network

  balanced-db:
    image: postgres:17-alpine
    container_name: balanced-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=balanced
      - POSTGRES_USER=balanced
      - POSTGRES_PASSWORD=balanced
    volumes:
      - balanced-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U balanced"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - balanced-network

networks:
  balanced-network:
    driver: bridge

volumes:
  balanced-db-data:
